service: shoreline

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-west-2
  environment:
    CHROME_PATH: ./headless-chrome/headless_shell

custom:
  webpackIncludeModules: true # disable auto including modules

plugins:
  - serverless-webpack

functions:
  run:
    description: Run headless Chromium
    memorySize: 1536
    timeout: 300
    handler: handler.run

resources:
  Outputs:
      LambdaRole:
        Value: 
          Ref: IamRoleLambdaExecution
        Export:
          Name: ${self:service}-${self:provider.stage}-lambda-role
